hash-format = "sha256"

[[files]]
file = "CHANGELOG.md"

[[files]]
file = "LICENSE"

[[files]]
file = "mods/amplified-nether.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/armored-foes.pw.toml"
metafile = true

[[files]]
file = "mods/atmospherics.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/banner-flags.pw.toml"
metafile = true

[[files]]
file = "mods/basicstorage.pw.toml"
metafile = true

[[files]]
file = "mods/bettercoppergolem.pw.toml"
metafile = true

[[files]]
file = "mods/biolith.pw.toml"
metafile = true

[[files]]
file = "mods/blaha-replushed.pw.toml"
metafile = true

[[files]]
file = "mods/breakerplacer.pw.toml"
metafile = true

[[files]]
file = "mods/buildcraftrefabricated.pw.toml"
metafile = true

[[files]]
file = "mods/cats-dont-care.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/chisel-reborn.pw.toml"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
metafile = true

[[files]]
file = "mods/cinderscapes.pw.toml"
metafile = true

[[files]]
file = "mods/clifftree.pw.toml"
metafile = true

[[files]]
file = "mods/climate-rivers.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/companion.pw.toml"
metafile = true

[[files]]
file = "mods/create-alloyed.pw.toml"
metafile = true

[[files]]
file = "mods/create-fly.pw.toml"
metafile = true

[[files]]
file = "mods/cryonicconfig.pw.toml"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
metafile = true

[[files]]
file = "mods/delight-lib.pw.toml"
metafile = true

[[files]]
file = "mods/directional_melons.pw.toml"
metafile = true

[[files]]
file = "mods/dyed-flames.pw.toml"
metafile = true

[[files]]
file = "mods/echo-chest.pw.toml"
metafile = true

[[files]]
file = "mods/enchanted-vertical-slabs.pw.toml"
metafile = true

[[files]]
file = "mods/ender-zoology.pw.toml"
metafile = true

[[files]]
file = "mods/energized-power-fd.pw.toml"
metafile = true

[[files]]
file = "mods/energized-power.pw.toml"
metafile = true

[[files]]
file = "mods/extended-drawers-extensions.pw.toml"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fantastic-wings.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes-beekeeper-hut-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes-flowery-mooblooms-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes.pw.toml"
metafile = true

[[files]]
file = "mods/frozenlib.pw.toml"
metafile = true

[[files]]
file = "mods/hang-glider.pw.toml"
metafile = true

[[files]]
file = "mods/harder-eye-of-ender.pw.toml"
metafile = true

[[files]]
file = "mods/headpat.pw.toml"
metafile = true

[[files]]
file = "mods/illager-invasion.pw.toml"
metafile = true

[[files]]
file = "mods/improved-village-placement.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/jetpacks-techreborn.pw.toml"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
metafile = true

[[files]]
file = "mods/kleeslabs.pw.toml"
metafile = true

[[files]]
file = "mods/lanterns-bow.pw.toml"
metafile = true

[[files]]
file = "mods/laseredstone.pw.toml"
metafile = true

[[files]]
file = "mods/lava-boats.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/mfvapi.pw.toml"
metafile = true

[[files]]
file = "mods/mobexplosiongriefinggamerule.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/more-chest-variants-lieonlion.pw.toml"
metafile = true

[[files]]
file = "mods/more-delight.pw.toml"
metafile = true

[[files]]
file = "mods/nameless-trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/natural-sizes.pw.toml"
metafile = true

[[files]]
file = "mods/new-linked-chests.pw.toml"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
metafile = true

[[files]]
file = "mods/omnihopper.pw.toml"
metafile = true

[[files]]
file = "mods/portable-hole.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/quickleafdecay.pw.toml"
metafile = true

[[files]]
file = "mods/reborncore.pw.toml"
metafile = true

[[files]]
file = "mods/reconnectible-chains.pw.toml"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/respawning-animals.pw.toml"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
metafile = true

[[files]]
file = "mods/rrv.pw.toml"
metafile = true

[[files]]
file = "mods/rsrreforged.pw.toml"
metafile = true

[[files]]
file = "mods/rustic-delight.pw.toml"
metafile = true

[[files]]
file = "mods/shine.pw.toml"
metafile = true

[[files]]
file = "mods/skeleton-ai-fix.pw.toml"
metafile = true

[[files]]
file = "mods/snuffles-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spiky-spikes.pw.toml"
metafile = true

[[files]]
file = "mods/tech-extensions.pw.toml"
metafile = true

[[files]]
file = "mods/techreborn.pw.toml"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
metafile = true

[[files]]
file = "mods/the-roads-more-travelled.pw.toml"
metafile = true

[[files]]
file = "mods/tool-trims-mod.pw.toml"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
metafile = true

[[files]]
file = "mods/traverse.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets-updated.pw.toml"
metafile = true

[[files]]
file = "mods/underlay.pw.toml"
metafile = true

[[files]]
file = "mods/universal-enchants.pw.toml"
metafile = true

[[files]]
file = "mods/variants-and-ventures.pw.toml"
metafile = true

[[files]]
file = "mods/wilder-wild.pw.toml"
metafile = true

[[files]]
file = "mods/wits.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true
