name = "Cute Cars"
author = "CuteCarsMC"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f187b7bddba41983584d0e767ce7b71d17b707158f565d24aab1df61638587d4"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
