name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    if: github.repository == 'SillyCarsMC/SillyCars'
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5.0.0
      - name: Set up Java
        uses: actions/setup-java@v5.1.0
        with:
          distribution: 'microsoft'
          java-version: 21
      - name: Setup Go
        uses: actions/setup-go@v6.1.0
        with:
          go-version: '1.25.5'
      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@52b12301
      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          name: artifacts
          path: out
      - name: Upload Pages Artifacts
        uses: actions/upload-pages-artifact@v4.0.0
        id: deployment
        with:
          path: build
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.repository == 'SillyCarsMC/SillyCars'
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4.0.5